app/routes.php
<?php

Route::group(['before' => 'auth|admin'], function()
{

    Route::resource('/', 'HomeController');


    Route::get('donation/donor/{donor}/event/{event}', 'DonationController@store');

    Route::get('donor/{donor}/add', 'DonationController@displayDonationForUser');

    Route::get('donor/search', ['as' => 'donor.search', 'uses' => 'DonorController@displaySearch']);
    Route::post('find/donor',  ['as' => 'donor/display', 'uses' => 'DonorController@findUser']);

    Route::get('donation/event/{event}/add', ['as' => 'donation/event', 'uses' => 'DonationController@displayDonationForEvent']);

    Route::post('event/toggle','DonationEventController@toggleDonationEvent');

     Route::post('donor/checkEligibility', ['as' => 'donor/checkEligibility', 'uses' => 'DonationController@checkEligibility']);

    Route::resource('donor', 'DonorController');
    Route::resource('donors', 'DonorController');
    Route::get('donor/add', ['as' => 'donor.add', 'uses' => 'DonorController@displayAddDonor']);
    Route::post('donor/{donor}/destroy', 'DonorController@destroy');
    Route::post('donor/{donor}/resetPassword', 'DonorController@resetPassword');



    Route::resource('event', 'DonationEventController');
    Route::resource('events', 'DonationEventController');
    Route::get('event/add', ['as' => 'event.add', 'uses' => 'DonationEventController@create']);
    Route::post('event/{event}/destroy', 'DonationEventController@destroy');

    Route::resource('donation', 'DonationController');
    Route::get('reserves', ['as' => 'reserves.index', 'uses' => 'DonationController@displayReserves']);
    Route::get('reserves/getReserves', 'DonationController@getReserves');
    Route::get('reserves/cities', ['as' => 'reserves.cities', 'uses' => 'DonationController@displayCityReserves']);
    Route::get('reserves/getCityReserves', 'DonationController@getCityReserves');


    Route::post('reserves/getReservesForEvent', 'DonationController@getReservesForEvent');
    Route::get('reserves/getDonorLocations', 'DonorController@getDonorLocations');

    Route::resource('user', 'UserController');
    Route::resource('users', 'UserController');
    Route::get('user/{user}', 'UserController@edit');


    Route::resource('notification', 'NotificationController');
    Route::post('notification/send', 'NotificationController@sendNotification');

});

Route::group(['before' => 'auth'], function(){

    Route::get('profile/index', ['as' => 'profile.index', 'uses' => 'DonorController@displayPublicIndex']);
    Route::get('profile/{donor}', ['as' => 'profile', 'uses' => 'DonorController@displayPublicProfile']);


});

Route::get('login', 'SessionController@create');
Route::get('logout', 'SessionController@destroy');
Route::resource('sessions', 'SessionController');

app/models/Donor.php
<?php

use Illuminate\Auth\UserInterface;
use Illuminate\Auth\Reminders\RemindableInterface;

class Donor extends Eloquent implements UserInterface, RemindableInterface {

	/**
	 * The database table used by the model.
	 *
	 * @var string
	 */
	protected $table = 'donors';
    protected $softDelete = true;


    protected $fillable = array(
                                'id',
                                'name',
                                'emb',
                                'city',
                                'gender',
                                'bloodtype',
                                'address',
                                'email',
                                'telephone',
                                'password',
                                'email',
                                'staff_fk',
                                'isadmin');



    public function events(){

    return $this->hasManyThrough('DonationEvent', 'Donor');

    }

	/**
	 * The attributes excluded from the model's JSON form.
	 *
	 * @var array
	 */
	protected $hidden = array('password');



    /**
	 * Get the unique identifier for the user.
	 *
	 * @return mixed
	 */
	public function getAuthIdentifier()
	{
		return $this->getKey();
	}

	/**
	 * Get the password for the user.
	 *
	 * @return string
	 */
	public function getAuthPassword()
	{
		return $this->password;
	}

	/**
	 * Get the e-mail address where password reminders are sent.
	 *
	 * @return string
	 */
	public function getReminderEmail()
	{
		return $this->email;
	}


    public function getRememberToken()
    {
        return $this->remember_token;
    }

    public function setRememberToken($value)
    {
        $this->remember_token = $value;
    }

    public function getRememberTokenName()
    {
        return 'remember_token';
    }



    public function donations()
    {
        return $this->hasMany('Donation', 'donor_fk');
    }

    public static function getBloodtype($userId){

        $donorInfo = Donor::find($userId);

        $bloodType = $donorInfo->bloodtype;

        return $bloodType;

     }

}

app/controllers/DonorController.php
<?php

class DonorController extends BaseController {

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
      public function index()
	{
        $donors = Donor::where('isadmin', '=', '0')->orderBy('name', 'ASC')->paginate(10);

        foreach($donors as $donor){
            $dateOfLastDonation = Donation::where('donor_fk', '=', $donor->id)->orderBy('created_at', 'DESC')->pluck('created_at');

            if(isset($dateOfLastDonation)) {
                $dateOfLastDonation = $dateOfLastDonation->toFormattedDateString();
            }
            else {
                $dateOfLastDonation = 'Нема дарувано';
            }
            $donor['lastDonation'] = $dateOfLastDonation;


    }

        return View::make('donor.index')->with(array('donors' => $donors, 'title' => 'Целосна листа на крводарители'));

	}


	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		//
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store()
	{
       $rules = array(
                'name' => 'required|min:4',
                'city' => 'required',
                'emb' => 'required|unique:donors,emb|numeric',
                'email' => 'required|email|unique:donors,name',
                'telephone' => 'required',
                'address' => 'required',
                'password' => 'required',
                'passwordConfirmation' => 'same:password'
            );

        $niceNames = array(
                'name' => 'име',
                'city' => 'град',
                'emb' => 'ЕМБГ',
                'email' => 'e-mail',
                'telephone' => 'телефон',
                'address' => 'адреса',
                'password' => 'лозинка',
                'passwordConfirmation' => 'потврда за лозинка'
        );

        $validator = Validator::make(Input::all(), $rules);
        $validator->setAttributeNames($niceNames);

        if (!$validator->fails()) {


        $id = str_random(50);
        $user = new Donor();

        $user->id = $id;
        $user->fill(Input::all());

        $hashedPassword = Hash::make(Input::get('password'));
        $user->password = $hashedPassword;

        $user->save();

        return Redirect::to('donor');
        }
        else return Redirect::to('donor/add')->withErrors($validator)->withInput();
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
        $donor = Donor::find($id);

        if($id == 'add'){
           return $this->displayAddDonor();
        }

        if($donor) {

             $donations = Donor::find($id)->donations;

            foreach($donations as $donation) {
                $donation->donationDate = $donation->created_at->toFormattedDateString();
            }

             $donationCount = Donor::find($id)->donations->count();
             $events = DonationEvent::all();

            	return  View::make('donor.profile')->with(array(
                                                             'donor' => $donor,
                                                             'donations' => $donations,
                                                             'donationCount' => $donationCount,
                                                             'events' => $events
                                                               ));
        }
        else {
            $donor = 'empty';

            return  View::make('donor.profile')->with(array(
                'donor' => $donor
            ));
        }

        }




    public function displayPublicProfile($id){

            $donor = Donor::find($id);

            $userId = Session::get('userId');
            $adminStatus = Session::get('adminStatus');

            if(($donor && $donor->id == $userId) || $donor && $adminStatus == 1) {

                $donations = Donor::find($id)->donations;
                $eligibilityInfo = $this->checkEligibility($id);
                foreach($donations as $donation) {
                    $donation->donationDate = $donation->created_at->toFormattedDateString();
                }

                $donationCount = Donor::find($id)->donations->count();
                $events = DonationEvent::all();

                return  View::make('donor.public.profile')->with(array(
                    'donor' => $donor,
                    'donations' => $donations,
                    'donationCount' => $donationCount,
                    'events' => $events,
                    'eligibilityInfo' => $eligibilityInfo
                ));
            }
            else {
                $donor = 'empty';

                return  View::make('donor.public.profile')->with(array(
                    'donor' => $donor
                ));
            }

        }


    public function checkEligibility($userId){



            $donorGender = Donor::where('id', '=',$userId)->pluck('gender');

            /* Get the most recent donation */

            $dateOfLastDonation = Donation::where('donor_fk', '=', $userId)->orderBy('created_at', 'DESC')->pluck('created_at');




            /* If the donor has no prior donations, skip everything */
            if(isset($dateOfLastDonation)){

                $currentDate = \Carbon\Carbon::now();

                $monthsPassed = $currentDate->diffInMonths($dateOfLastDonation);

                /* 3 months need to pass for males to be eligible for donating again;
                   4 months for females;  */

                if(($donorGender == 1 && $monthsPassed < 3) || ($donorGender == 0 && $monthsPassed < 4 )){

                    $lastDonation = $dateOfLastDonation->toFormattedDateString();

                    if($donorGender == 0){
                        $nextDonation = $dateOfLastDonation->addMonths(4);  // Add 4 months for females
                    }

                    else{
                        $nextDonation = $dateOfLastDonation->addMonths(3);  // Add 3 months for males
                    }

                    $timeLeft = $currentDate->diffInDays($nextDonation);
                    $nextDonation = $nextDonation->toFormattedDateString();

                    $eligibilityInfo = ['eligible' => '0', 'nextDonation' => $nextDonation, 'lastDonation' => $lastDonation, 'timeLeft' => $timeLeft];

                    return $eligibilityInfo;
                }
            }
            else{
                $eligibilityInfo = ['eligible' => '1', 'nextDonation' => '', 'lastDonation' => '', 'timeLeft' => ''];
                return $eligibilityInfo;
            }


    }



    public function displayPublicIndex(){

        $userId = Session::get('userId');

        $dateOfLastDonation = Donation::where('donor_fk', '=', $userId)->orderBy('created_at', 'DESC')->pluck('created_at');


        $events = DonationEvent::where('isactive', '=', '1')->orderBy('start_time', 'ASC')->get();

       foreach($events as $event){
               $tidyStartTime = new \Carbon\Carbon($event->start_time);
               $tidyEndTime = new \Carbon\Carbon($event->end_time);

               $event->start_time = $tidyStartTime->format('H:i \\- M d\\, Y '); // Hour, Minute - Day (numerical), Month (short name), Year
               $event->end_time = $tidyEndTime->format('H:i \\- M d\\, Y ');

       }



        return View::make('donor.public.index')->with(['events' => $events]);
    }





	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{

        $donorInfo = Donor::find($id);

        if($donorInfo){
            return View::make('donor.edit')->with('donor', $donorInfo);
        }

        else {
            $donorInfo = 'empty';
            return View::make('donor.edit')->with('donor', $donorInfo);
        }
    }

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{

        $donor = Donor::find($id);

        $rules = array(
            'name' => 'required|min:4',
            'city' => 'required',
            'emb' => 'required|unique:donors,emb|numeric',
            'email' => 'required|email|unique:donors,name',
            'telephone' => 'required',
            'address' => 'required'
        );

        $niceNames = array(
            'name' => 'име',
            'city' => 'град',
            'emb' => 'ЕМБГ',
            'email' => 'e-mail',
            'telephone' => 'телефон',
            'address' => 'адреса'
        );

        /* Remove the mandatory unique rule for the EMB if it's not changed. Too lazy to write a more elegant way of solving this. */

        if(Input::get('emb') == $donor->emb ){
            $rules['emb'] = '';
        }


        $validator = Validator::make(Input::all(), $rules);
        $validator->setAttributeNames($niceNames);

        if (!$validator->fails()) {

        if($donor){

            $donor->fill(Input::all());
            $donor->save();

            return Redirect::to('donor/' . $donor->id);
        }

        }

        else {
         return Redirect::to('donor/' . $donor->id . '/edit')->withErrors($validator)->withInput();
        }

    }

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id){

        $user = Donor::find($id);

        if($user){
        $result = $user->delete();

            if($result != 0){
                echo json_encode(true);
            }
            else{
                echo json_encode(false);
            }
        }

	}


    public function resetPassword(){

        $donorId = Input::get('id');

        $donor = Donor::find($donorId);

        if($donor){

             $newPassword = str_random(50);

             $hashedPassword = Hash::make($newPassword);

             $donor->password = $hashedPassword;

app/views/donor/add.blade.php
@extends('master')
@section('content')

<div class="title_wrapper">
    <h3 class="title">Додавање на крводарител</h3>
</div>
<div class="add_donor_wrapper">



{{ Form::open(['route' => 'donor.store']) }}

    <ul class="errors">
       @foreach($errors->all() as $message)
        <li>{{ $message }}</li>
      @endforeach
     </ul>
    <div class="add_donor_info">
<div class="personal_info">

         {{ Form::label('name', 'Име и презиме') }} <br />
         {{ Form::text('name', null, ['placeholder' => 'Име и презиме']) }}
         <br />


             {{ Form::label('gender', 'Пол') }} <br />
             {{ Form::select('gender', [
             '1' => 'Машки',
             '0' => 'Женски',
             ]
             ) }}

         <br/>
             {{ Form::label('emb', 'ЕМБГ') }} <br />
             {{ Form::text('emb', null, ['placeholder' => 'ЕМБГ']) }}
</div>

<div class="personal_info">
        {{ Form::label('city', 'Град') }} <br />
        {{ Form::select('city', [
        'Скопје' => 'Скопје',
        'Берово' => 'Берово',
        'Битола' => 'Битола',
        'Богданци' => 'Богданци',
        'Валандово' => 'Валандово',
        'Велес' => 'Велес',
        'Виница' => 'Виница',
        'Гевгелија' => 'Гевгелија',
        'Гостивар' => 'Гостивар',
        'Дебар' => 'Дебар',
        'Делчево' => 'Делчево',
        'Демир Капија' => 'Демир Капија',
        'Демир Хисар' => 'Демир Хисар',
        'Кавадарци' => 'Кавадарци',
        'Кичево' => 'Кичево',
        'Кочани' => 'Кочани',
        'Кратово' => 'Кратово',
        'Крива Паланка' => 'Крива Паланка',
        'Крушево' => 'Крушево',
        'Куманово' => 'Куманово',
        'Македонска Каменица' => 'Македонска Каменица',
        'Македонски Брод' => 'Македонски Брод',
        'Неготино' => 'Неготино',
        'Охрид' => 'Охрид',
        'Пехчево' => 'Пехчево',
        'Прилеп' => 'Прилеп',
        'Пробиштип' => 'Пробиштип',
        'Радовиш' => 'Радовиш',
        'Ресен' => 'Ресен',
        'Свети Николе' => 'Свети Николе',
        'Струга' => 'Струга',
        'Струмица' => 'Струмица',
        'Тетово' => 'Тетово',
        'Штип' => 'Штип'
        ]
    ) }}
        <br/>
         {{ Form::label('address', 'Адреса') }}
         <br/>
         {{ Form::text('address', null, ['placeholder' => 'Адреса']) }}
         <br/>

     {{ Form::label('bloodtype', 'Крвна група') }}
       <br/>
     {{ Form::select('bloodtype', [
     'A+' => 'A+',
     'A-' => 'A-',
     'B+' => 'B+',
     'AB+' => 'AB+',
     'AB-' => 'AB-',
     'O+' => 'O+',
     'O-' => 'O-'
     ]
     ) }}
</div>



   <div class="personal_info">

       {{ Form::label('email', 'E-mail') }}
       <br />
       {{ Form::text('email', null, ['placeholder' => 'Е-mail']) }}

       <br />
       {{ Form::label('telephone', 'Контакт телефон') }}
       <br />
       {{ Form::text('telephone', null, ['placeholder' => 'Контакт телефон']) }}
       {{ Form::text('staff_fk', Session::get('staffId'), ['hidden' => 'true']) }}

       <br />
       {{ Form::label('password', 'Лозинка') }}
       <br />
       {{ Form::password('password', null, ['placeholder' => 'Лозинка']) }}

       <br />
       {{ Form::label('passwordConfirmation', 'Потврда за лозинка') }}
       <br />
       {{ Form::password('passwordConfirmation', null, ['placeholder' => 'Лозинка']) }}




   </div>


<div class="clear"></div>
<br />
</div>
<div class="submit_wrapper">
    {{ Form::submit('Додади') }}
</div>

{{ Form::close() }}

</div>

@stop

app/views/donor/edit.blade.php
@extends('master')
@section('content')
{{ HTML::script('js/donor-script.js') }}
{{ HTML::script('js/lib/jquery.confirm.js') }}

<?php $errorImage = asset('images/google404.png'); ?>

@if($donor != 'empty' && !empty($donor))


<div class="title_wrapper">
    <h3 class="title">Промена на податоци за крводарител</h3>
</div>


<div class="add_donor_wrapper">
    <br/>
    <div class="outcome" id="outcome"></div>

    <ul class="errors">
        @foreach($errors->all() as $message)
        <li>{{ $message }}</li>
        @endforeach
    </ul>

    {{ Form::model($donor, ['method' => 'PATCH', 'route' => ['donor.update', $donor->id]]) }}



    <div class="add_donor_info">

        <br/>
        <div class="personal_info">

            {{ Form::label('name', 'Име и презиме') }} <br />
            {{ Form::text('name', null, ['placeholder' => 'Име и презиме']) }}
            <br />


            {{ Form::label('gender', 'Пол') }} <br />
            {{ Form::select('gender', [
            '1' => 'Машки',
            '0' => 'Женски',
            ], $donor->gender
            ) }}

            <br/>
            {{ Form::label('emb', 'ЕМБГ') }} <br />
            {{ Form::text('emb', null, ['placeholder' => 'ЕМБГ']) }}
        </div>

        <div class="personal_info">
            {{ Form::label('city', 'Град') }} <br />
            {{ Form::select('city', [
            'Скопје' => 'Скопје',
            'Берово' => 'Берово',
            'Битола' => 'Битола',
            'Богданци' => 'Богданци',
            'Валандово' => 'Валандово',
            'Велес' => 'Велес',
            'Виница' => 'Виница',
            'Гевгелија' => 'Гевгелија',
            'Гостивар' => 'Гостивар',
            'Дебар' => 'Дебар',
            'Делчево' => 'Делчево',
            'Демир Капија' => 'Демир Капија',
            'Демир Хисар' => 'Демир Хисар',
            'Кавадарци' => 'Кавадарци',
            'Кичево' => 'Кичево',
            'Кочани' => 'Кочани',
            'Кратово' => 'Кратово',
            'Крива Паланка' => 'Крива Паланка',
            'Крушево' => 'Крушево',
            'Куманово' => 'Куманово',
            'Македонска Каменица' => 'Македонска Каменица',
            'Македонски Брод' => 'Македонски Брод',
            'Неготино' => 'Неготино',
            'Охрид' => 'Охрид',
            'Пехчево' => 'Пехчево',
            'Прилеп' => 'Прилеп',
            'Пробиштип' => 'Пробиштип',
            'Радовиш' => 'Радовиш',
            'Ресен' => 'Ресен',
            'Свети Николе' => 'Свети Николе',
            'Струга' => 'Струга',
            'Струмица' => 'Струмица',
            'Тетово' => 'Тетово',
            'Штип' => 'Штип'
            ],
            $donor->city
            ) }}
            <br/>
            {{ Form::label('address', 'Адреса') }}
            <br/>
            {{ Form::text('address', null, ['placeholder' => 'Адреса']) }}
            <br/>

            {{ Form::label('bloodtype', 'Крвна група') }}
            <br/>
            {{ Form::select('bloodtype', [
            'A+' => 'A+',
            'A-' => 'A-',
            'B+' => 'B+',
            'AB+' => 'AB+',
            'AB-' => 'AB-',
            'O+' => 'O+',
            'O-' => 'O-'
            ]
            ) }}
        </div>



        <div class="personal_info">

            {{ Form::label('email', 'E-mail') }}
            <br />
            {{ Form::text('email', null, ['placeholder' => 'Е-mail']) }}

            <br />
            {{ Form::label('telephone', 'Контакт телефон') }}
            <br />
            {{ Form::text('telephone', null, ['placeholder' => 'Контакт телефон']) }}
            {{ Form::text('staff_fk', Session::get('staffId'), ['hidden' => 'true']) }}

        </div>
        <div class="personal_info">
    <hr/>
            {{ Form::label('', 'Избриши крводарител') }}
            <br />
            <input type="button" id="delete_donor" value="Избриши"/>
            <br />
            {{ Form::label('', 'Ресетирај лозинка') }}
            <br />
            <input type="button" id="reset_password" value="Ресетирај"/>


            {{ Form::text('donor_fk', $donor->id, ['id' => 'donor_fk', 'hidden' => 'true']) }}

        </div>

        <div class="clear"></div>
        <br/>
    </div>
    <div class="submit_wrapper">
        <br/>
        {{ Form::submit('Обнови') }}
    </div>

    {{ Form::close() }}

</div>

@else

<div class="profile_wrapper">

    <div class="not_found">
        <img src="{{ $errorImage }}"/>
        <br/>
        {{ 'Крводарителот не постои.'; }}
    </div>
</div>

@endif


@stop

app/views/donor/index.blade.php
@extends('master')

@section('content')

{{ HTML::script('js/users-script.js') }}
<div class="title_wrapper">
<h3 class="title">Листа на крводарители</h3>
</div>
<table class="flat_table flat_table_1">
    <thead>
    <th>Име</th>
    <th>Град</th>
    <th>Крвна група</th>
    <th>Последно дарување</th>
    </thead>
    <tbody class="search_results">

    @foreach ($donors as $donor)

    <tr>
        <td> {{  link_to_route('donor.show', $donor->name, $donor->id ) }} </td>

        <td> {{ $donor->city }} </td>

        <td> {{ $donor->bloodtype }} </td>

        <td> {{ $donor->lastDonation }} </td>

    </tr>

    @endforeach

    </tbody>


</table>

@if(isset($donors))
    {{ $donors->links(); }}
@endif


@stop

app/views/donor/profile.blade.php
@extends('master')
@section('content')

{{ HTML::script('js/donation-script.js') }}
<?php
    $errorImage = asset('images/google404.png');

?>
 @if (!empty($donor) && $donor != 'empty' )

<div class="title_wrapper"><h3 class="title">Профилот на {{ $donor->name }} </h3></div>



<div class="profile_wrapper">

    <div class="profile_buttons">

                <a href="{{ $donor->id  }}/add">
                    <div class="metro_button pink profile_button">
                        <img class="metro_icon" src="../images/adddonationicon.png"/>
                        <p class="button_text">додади дарување</p>
                    </div>
                </a>


                <a href="{{ $donor->id  }}/edit">
                    <div class="metro_button blue profile_button">
                        <img class="metro_icon" src="../images/editicon.png"/>
                        <p class="button_text">смени податоци</p>
                    </div>
                </a>

    </div>

    <div class="clear"></div>

    <br/>

 @if(!$donations->isEmpty())

    <div class="profile_info">

        <div class="search_results_wrapper donations ">
            <table class="flat_table flat_table_1 profile_table">
                <thead>
                <th>Град</th>
                <th>ЕМБГ</th>
                <th>Крвна група</th>
                <th>E-mail</th>
                <th>Телефон</th>
                </thead>
                <tbody class="search_results">
                <tr>
                    <td> {{ $donor->city }} </td>
                    <td> {{ $donor->emb }} </td>
                    <td> {{ $donor->bloodtype }} </td>
                    <td> {{ $donor->email }} </td>
                    <td> {{ $donor->telephone }} </td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>




    <div class="title_wrapper profile">
        <h4 class="title">
            {{ $donor->name }}
            @if($donor->gender == 0)
             дарувала
            @else
             дарувал
            @endif
            на следниве акции

        </h4></div>

    <div class="search_results_wrapper donations">
            <table class="flat_table flat_table_1">
                <thead>
                <th>#</th>
                <th>Настан</th>
                <th>Град</th>
                <th>Датум</th>
                </thead>
                <tbody class="search_results">
                 <?php

                      $count = 1;

                      foreach($donations as $donation){

                      foreach($events as $event){

                          if($donation->event_fk == $event->id)
                            if($count %2 != 0){
                                echo   '<tr class="odd">
                                     <td>' . $count . '</td>
                                     <td>' . '<a class="search_link" href="' . '../event'  . '/' .  $event->id . '">' . $event->name .'</a></td>'
                                    . '<td>' . $event->city . '</td>'
                                    . '<td>' . $donation->donationDate . '</td>'
                                    . '</tr>';


                            }
                            else{

                             echo   '<tr class="even">
                                     <td>' . $count . '</td>
                                     <td>' . '<a class="search_link" href="' . '../event'  . '/' .  $event->id . '">' . $event->name .'</a></td>'
                                     . '<td>' . $event->city . '</td>'
                                     . '<td>' . $donation->donationDate . '</td>'
                                     . '</tr>';


                            }


                        }
                          $count++;
                      }
                ?>
                </tbody>
            </table>
        </form>


    </div>



    @else

    <div class="title_wrapper profile">
        <h4 class="title">

            {{ $donor->name }} нема дарувано на ниедна акција.

        </h4></div>


    @endif
</div>



    @else

    <div class="profile_wrapper">

    <div class="not_found">
        <img src="{{ $errorImage }}"/>
        <br/>
        {{ 'Крводарителот не постои.'; }}
    </div>
    </div>

    @endif



@stop