app/routes.php
<?php

Route::group(['before' => 'auth|admin'], function()
{

    Route::resource('/', 'HomeController');


    Route::get('donation/donor/{donor}/event/{event}', 'DonationController@store');

    Route::get('donor/{donor}/add', 'DonationController@displayDonationForUser');

    Route::get('donor/search', ['as' => 'donor.search', 'uses' => 'DonorController@displaySearch']);
    Route::post('find/donor',  ['as' => 'donor/display', 'uses' => 'DonorController@findUser']);

    Route::get('donation/event/{event}/add', ['as' => 'donation/event', 'uses' => 'DonationController@displayDonationForEvent']);

    Route::post('event/toggle','DonationEventController@toggleDonationEvent');

     Route::post('donor/checkEligibility', ['as' => 'donor/checkEligibility', 'uses' => 'DonationController@checkEligibility']);

    Route::resource('donor', 'DonorController');
    Route::resource('donors', 'DonorController');
    Route::get('donor/add', ['as' => 'donor.add', 'uses' => 'DonorController@displayAddDonor']);
    Route::post('donor/{donor}/destroy', 'DonorController@destroy');
    Route::post('donor/{donor}/resetPassword', 'DonorController@resetPassword');



    Route::resource('event', 'DonationEventController');
    Route::resource('events', 'DonationEventController');
    Route::get('event/add', ['as' => 'event.add', 'uses' => 'DonationEventController@create']);
    Route::post('event/{event}/destroy', 'DonationEventController@destroy');

    Route::resource('donation', 'DonationController');
    Route::get('reserves', ['as' => 'reserves.index', 'uses' => 'DonationController@displayReserves']);
    Route::get('reserves/getReserves', 'DonationController@getReserves');
    Route::get('reserves/cities', ['as' => 'reserves.cities', 'uses' => 'DonationController@displayCityReserves']);
    Route::get('reserves/getCityReserves', 'DonationController@getCityReserves');


    Route::post('reserves/getReservesForEvent', 'DonationController@getReservesForEvent');
    Route::get('reserves/getDonorLocations', 'DonorController@getDonorLocations');

    Route::resource('user', 'UserController');
    Route::resource('users', 'UserController');
    Route::get('user/{user}', 'UserController@edit');


    Route::resource('notification', 'NotificationController');
    Route::post('notification/send', 'NotificationController@sendNotification');

});

Route::group(['before' => 'auth'], function(){

    Route::get('profile/index', ['as' => 'profile.index', 'uses' => 'DonorController@displayPublicIndex']);
    Route::get('profile/{donor}', ['as' => 'profile', 'uses' => 'DonorController@displayPublicProfile']);


});

Route::get('login', 'SessionController@create');
Route::get('logout', 'SessionController@destroy');
Route::resource('sessions', 'SessionController');

app/views/event/add.blade.php
@extends('master')
@section('content')
{{ HTML::script('js/events-script.js') }}
{{ HTML::script('js/lib/bootstrap-datepicker.js') }}
{{ HTML::script('js/lib/jquery.timepicker.js') }}
{{ HTML::script('js/lib/jquery.datepair.js') }}
{{ HTML::script('js/lib/jquery.ptTimeSelect.js') }}
{{ HTML::style('js/lib/css/jquery.ptTimeSelect.css') }}
{{ HTML::style('js/lib/css/jquery.timepicker.css') }}
{{ HTML::style('js/lib/css/bootstrap-datepicker.css') }}


<div class="title_wrapper">
    <h3 class="title">Додавање на крводарителна акција</h3>
</div>
<div class="add_event_wrapper">

    <ul class="errors">
        @foreach($errors->all() as $message)
        <li>{{ $message }}</li>
        @endforeach
    </ul>

    {{ Form::open(['route' => 'event.store']) }}

    <div class="add_donor_info">

        <div class="personal_info">

            {{ Form::label('name', 'Име на настан') }} <br />

            {{ Form::text('name', null, [ 'placeholder' => 'Име на настан'])  }}
</div>
        <div class="personal_info" >

            {{ Form::label('city', 'Град') }}
            <br />

            {{ Form::select('city', [
            'Скопје' => 'Скопје',
            'Берово' => 'Берово',
            'Битола' => 'Битола',
            'Богданци' => 'Богданци',
            'Валандово' => 'Валандово',
            'Велес' => 'Велес',
            'Виница' => 'Виница',
            'Гевгелија' => 'Гевгелија',
            'Гостивар' => 'Гостивар',
            'Дебар' => 'Дебар',
            'Делчево' => 'Делчево',
            'Демир Капија' => 'Демир Капија',
            'Демир Хисар' => 'Демир Хисар',
            'Кавадарци' => 'Кавадарци',
            'Кичево' => 'Кичево',
            'Кочани' => 'Кочани',
            'Кратово' => 'Кратово',
            'Крива Паланка' => 'Крива Паланка',
            'Крушево' => 'Крушево',
            'Куманово' => 'Куманово',
            'Македонска Каменица' => 'Македонска Каменица',
            'Македонски Брод' => 'Македонски Брод',
            'Неготино' => 'Неготино',
            'Охрид' => 'Охрид',
            'Пехчево' => 'Пехчево',
            'Прилеп' => 'Прилеп',
            'Пробиштип' => 'Пробиштип',
            'Радовиш' => 'Радовиш',
            'Ресен' => 'Ресен',
            'Свети Николе' => 'Свети Николе',
            'Струга' => 'Струга',
            'Струмица' => 'Струмица',
            'Тетово' => 'Тетово',
            'Штип' => 'Штип'
            ]
            ) }}

            <br/>

            {{ Form::label('address', 'Адреса') }}
            <br/>
            {{ Form::text('address', null, ['placeholder' => 'Адреса']) }}
            <br/>


        </div>

    <div class="personal_info">
    <p id="datetimepicker">
        {{ Form::label('start_date', 'Времетраење - од') }} <br/>
        {{ Form::text('start_date', '1/1/2014', array('class' => 'date start', 'id' => 'dateselector', 'readonly')) }}
        {{ Form::text('start_time', '12:00', array('class' => 'time start', 'id' => 'timeselector', )) }}
        <br/>
        {{ Form::label('start_date', 'до') }} <br/>
        {{ Form::text('end_date', '1/1/2014', array('class' => 'date end', 'id' => 'dateselector', 'readonly')) }}
        {{ Form::text('end_time', '13:00', array('class' => 'time end', 'id' => 'timeselector', )) }}



    </p>
        </div>
        <div class="clear"></div>
    </div>
    <div class="submit_wrapper">
        {{ Form::submit('Додади') }}
        <br/>
    </div>

    {{ Form::close() }}

</div>



<script>
    // initialize input widgets first
    $('#datetimepicker .time').timepicker({
        'showDuration': true,
        'timeFormat': 'G:i'
    });

    $('#datetimepicker .date').datepicker({
        'format': 'd/m/yyyy',
        'autoclose': true
    });

    // initialize datepair
    $('#datetimepicker').datepair();
</script>

@stop

app/views/event/details.blade.php
@extends('master')
@section('content')

<script type="text/javascript" src="https://www.google.com/jsapi"></script>
{{ HTML::script('js/event-script.js') }}

<?php $errorImage = asset('images/google404.png'); ?>

@if(isset($event))
<div class="title_wrapper">
    <h3 class="title">Детали за акцијата {{ $event->name }} </h3>
</div>



<div class="profile_wrapper">

        <div class="profile_buttons">

            <a href="../donation/event/{{ $event->id }}/add">
                <div class="metro_button pink profile_button event">
                    <img class="metro_icon" src="../images/adddonationicon.png"/>
                    <p class="button_text">додади дарување</p>
                </div>
            </a>


            <a href="{{ $event->id  }}/edit">
                <div class="metro_button blue profile_button event">
                    <img class="metro_icon" src="../images/editicon.png"/>
                    <p class="button_text">смени податоци</p>
                </div>
            </a>

             <a id="toggle_is_active" href="javascript:;"">
                <div class="metro_button violet profile_button event">
                    @if($event->isactive == 0)
                    <img id="toggle_image" class="metro_icon" src="../images/unlockicon.png"/>
                    <p id="toggle_text"  class="button_text">отвори акција</p>

                    <input name="event_fk" value="{{ $event->id }}" type="text" hidden/>

                    @else

                    <img id="toggle_image" class="metro_icon" src="../images/lockicon.png"/>
                    <p id="toggle_text"  class="button_text">затвори акција</p>

                    @endif

                </div>
            </a>

        </div>

        <div class="clear"></div>

        <div class="profile_info">
            <div class="search_results_wrapper donations ">
                <table class="flat_table flat_table_1 profile_table">
                <thead>
                <th>Град</th>
                <th>Почнува</th>
                <th>Завршува</th>
                <th>Затворена</th>
                </thead>
                <tbody class="search_results">
                <tr>
                    <td>{{ $event->city }}</td>
                    <td>{{ $event->start_time }}</td>
                    <td>{{ $event->end_time }}</td>
                    <td id="toggle_status">
                        @if($event->isactive == 0)
                            {{ 'Да' }}
                        @else
                            {{ 'Не' }}
                        @endif
                    </td>
                </tr>
                </tbody>
            </table>

        </div>
        </div>


        <div class="clear"></div>
    <div class="title_wrapper details">
        <h4 class="title">Резерви на крв на државно ниво - Секторски дијаграм</h4>
    </div>

        <div id="empty_chart" class="outcome"></div>

        <div class="chart_wrapper" id="chart_wrapper">

            <div id="pie_chart" class="chart"></div>
        </div>




        {{ Form::text('event_fk', $event->id, ['hidden' => 'true' ]) }}


    </div>





@else
        <div class="profile_wrapper">

        <div class="not_found">
            <img src="{{ $errorImage }}"/>
            <br/>
        {{ 'Акцијата не постои.'; }}
        </div>
        </div>

@endif





@stop

app/views/event/edit.blade.php
@extends('master')
@section('content')
<script type="text/javascript" src="https://www.google.com/jsapi"></script>
{{ HTML::script('js/event-script.js') }}
{{ HTML::script('js/lib/bootstrap-datepicker.js') }}
{{ HTML::script('js/lib/jquery.confirm.js') }}
{{ HTML::script('js/lib/jquery.timepicker.js') }}
{{ HTML::script('js/lib/jquery.datepair.js') }}
{{ HTML::script('js/lib/jquery.ptTimeSelect.js') }}
{{ HTML::style('js/lib/css/jquery.ptTimeSelect.css') }}
{{ HTML::style('js/lib/css/jquery.timepicker.css') }}
{{ HTML::style('js/lib/css/bootstrap-datepicker.css') }}

<?php $errorImage = asset('images/google404.png'); ?>


@if($event != 'empty' && !empty($event))

<div class="title_wrapper">
    <h3 class="title">Промена на крводарителна акција</h3>
</div>
<div class="add_event_wrapper">
    <div class="outcome" id="outcome"></div>

    <ul class="errors">
        @foreach($errors->all() as $message)
        <li>{{ $message }}</li>
        @endforeach
    </ul>

    <div class="outcome">
        <?php
            $dateError = Session::get('dateError', '');
            Session::forget('dateError');
        ?>
        {{ $dateError }}
        <br/>
    </div>

    {{ Form::model($event, ['method' => 'PATCH', 'route' => ['event.update', $event->id]]) }}

    <div class="add_donor_info">

        <div class="personal_info">

            {{ Form::label('name', 'Име на настан') }} <br />

            {{ Form::text('name', null, [ 'placeholder' => 'Име на настан', 'id' => 'event_name'])  }}
        </div>
        <div class="personal_info" >

            {{ Form::label('city', 'Град') }}
            <br />

            {{ Form::select('city', [
            'Скопје' => 'Скопје',
            'Берово' => 'Берово',
            'Битола' => 'Битола',
            'Богданци' => 'Богданци',
            'Валандово' => 'Валандово',
            'Велес' => 'Велес',
            'Виница' => 'Виница',
            'Гевгелија' => 'Гевгелија',
            'Гостивар' => 'Гостивар',
            'Дебар' => 'Дебар',
            'Делчево' => 'Делчево',
            'Демир Капија' => 'Демир Капија',
            'Демир Хисар' => 'Демир Хисар',
            'Кавадарци' => 'Кавадарци',
            'Кичево' => 'Кичево',
            'Кочани' => 'Кочани',
            'Кратово' => 'Кратово',
            'Крива Паланка' => 'Крива Паланка',
            'Крушево' => 'Крушево',
            'Куманово' => 'Куманово',
            'Македонска Каменица' => 'Македонска Каменица',
            'Македонски Брод' => 'Македонски Брод',
            'Неготино' => 'Неготино',
            'Охрид' => 'Охрид',
            'Пехчево' => 'Пехчево',
            'Прилеп' => 'Прилеп',
            'Пробиштип' => 'Пробиштип',
            'Радовиш' => 'Радовиш',
            'Ресен' => 'Ресен',
            'Свети Николе' => 'Свети Николе',
            'Струга' => 'Струга',
            'Струмица' => 'Струмица',
            'Тетово' => 'Тетово',
            'Штип' => 'Штип'
            ],
            $event->city) }}

            <br/>

            {{ Form::label('address', 'Адреса') }}
            <br/>
            {{ Form::text('address', null, ['placeholder' => 'Адреса']) }}
            <br/>


        </div>

        <div class="personal_info">
            <p id="datetimepicker">
                {{ Form::label('start_date', 'Времетраење - од') }} <br/>
                {{ Form::text('start_date', $event->startDate, array('class' => 'date start', 'id' => 'dateselector', 'readonly')) }}
                {{ Form::text('start_time', $event->startTime, array('class' => 'time start', 'id' => 'timeselector', )) }}
                <br/>
                {{ Form::label('start_date', 'до') }} <br/>
                {{ Form::text('end_date', $event->endDate, array('class' => 'date end', 'id' => 'dateselector', 'readonly')) }}
                {{ Form::text('end_time', $event->endTime, array('class' => 'time end', 'id' => 'timeselector', )) }}

        <hr/>
            {{ Form::text('event_fk', $event->id, ['id' => 'event_fk', 'hidden' => 'true']) }}
            {{ Form::label('', 'Избриши акција') }}
            <br />
            <input type="button" id="delete_event" value="Избриши"/>

            </p>
        </div>
        <div class="clear"></div>
    </div>
    <div class="submit_wrapper">
        <br/>
        {{ Form::submit('Обнови') }}
    </div>

    {{ Form::close() }}

</div>

@else

<div class="profile_wrapper">

    <div class="not_found">
        <img src="{{ $errorImage }}"/>
        <br/>
        {{ 'Акцијата не постои.'; }}
    </div>
</div>


@endif

<script>
    // initialize input widgets first
    $('#datetimepicker .time').timepicker({
        'showDuration': true,
        'timeFormat': 'G:i',
        'defaultTimeDelta': 18000000
    });

    $('#datetimepicker .date').datepicker({
        'format': 'd/m/yyyy',
        'autoclose': true
    });

    // initialize datepair
    $('#datetimepicker').datepair();
</script>

@stop

app/views/event/index.blade.php
@extends('master')

@section('content')


<div class="title_wrapper">
    <h3 class="title">Крводарителни акции</h3>
</div>
<table class="flat_table flat_table_1">
    <thead>
    <th>Име</th>
    <th>Град</th>
    <th>Број на дарувања</th>
    <th>Завршена</th>
    </thead>
    <tbody class="search_results">

    @foreach ($events as $event)

    <tr>
        <td> {{  link_to_route('event.show', $event->name, $event->id ) }} </td>

        <td> {{ $event->city }} </td>

        <td class="table_center_content"> {{ $event->donationsCount }} </td>

        <td class="table_center_content">
            @if ($event->isactive == 1)

                {{ 'Не' }}

            @else

                {{ 'Да' }}

            @endif
        </td>

    </tr>

    @endforeach

    </tbody>


</table>

@if(isset($events))
 {{ $events->links(); }}
@endif


@stop