app/routes.php
<?php

Route::group(['before' => 'auth|admin'], function()
{

    Route::resource('/', 'HomeController');


    Route::get('donation/donor/{donor}/event/{event}', 'DonationController@store');

    Route::get('donor/{donor}/add', 'DonationController@displayDonationForUser');

    Route::get('donor/search', ['as' => 'donor.search', 'uses' => 'DonorController@displaySearch']);
    Route::post('find/donor',  ['as' => 'donor/display', 'uses' => 'DonorController@findUser']);

    Route::get('donation/event/{event}/add', ['as' => 'donation/event', 'uses' => 'DonationController@displayDonationForEvent']);

    Route::post('event/toggle','DonationEventController@toggleDonationEvent');

     Route::post('donor/checkEligibility', ['as' => 'donor/checkEligibility', 'uses' => 'DonationController@checkEligibility']);

    Route::resource('donor', 'DonorController');
    Route::resource('donors', 'DonorController');
    Route::get('donor/add', ['as' => 'donor.add', 'uses' => 'DonorController@displayAddDonor']);
    Route::post('donor/{donor}/destroy', 'DonorController@destroy');
    Route::post('donor/{donor}/resetPassword', 'DonorController@resetPassword');



    Route::resource('event', 'DonationEventController');
    Route::resource('events', 'DonationEventController');
    Route::get('event/add', ['as' => 'event.add', 'uses' => 'DonationEventController@create']);
    Route::post('event/{event}/destroy', 'DonationEventController@destroy');

    Route::resource('donation', 'DonationController');
    Route::get('reserves', ['as' => 'reserves.index', 'uses' => 'DonationController@displayReserves']);
    Route::get('reserves/getReserves', 'DonationController@getReserves');
    Route::get('reserves/cities', ['as' => 'reserves.cities', 'uses' => 'DonationController@displayCityReserves']);
    Route::get('reserves/getCityReserves', 'DonationController@getCityReserves');


    Route::post('reserves/getReservesForEvent', 'DonationController@getReservesForEvent');
    Route::get('reserves/getDonorLocations', 'DonorController@getDonorLocations');

    Route::resource('user', 'UserController');
    Route::resource('users', 'UserController');
    Route::get('user/{user}', 'UserController@edit');


    Route::resource('notification', 'NotificationController');
    Route::post('notification/send', 'NotificationController@sendNotification');

});

Route::group(['before' => 'auth'], function(){

    Route::get('profile/index', ['as' => 'profile.index', 'uses' => 'DonorController@displayPublicIndex']);
    Route::get('profile/{donor}', ['as' => 'profile', 'uses' => 'DonorController@displayPublicProfile']);


});

Route::get('login', 'SessionController@create');
Route::get('logout', 'SessionController@destroy');
Route::resource('sessions', 'SessionController');

app/models/User.php
<?php

use Illuminate\Auth\UserInterface;
use Illuminate\Auth\Reminders\RemindableInterface;

class User extends Eloquent implements UserInterface, RemindableInterface {

	/**
	 * The database table used by the model.
	 *
	 * @var string
	 */
	protected $table = 'donors';
    protected $softDelete = true;
    protected $fillable = array(
                                'id',
                                'name',
                                'password',
                                'email');


	/**
	 * The attributes excluded from the model's JSON form.
	 *
	 * @var array
	 */
	protected $hidden = array('password');

	/**
	 * Get the unique identifier for the user.
	 *
	 * @return mixed
	 */
	public function getAuthIdentifier()
	{
		return $this->getKey();
	}

	/**
	 * Get the password for the user.
	 *
	 * @return string
	 */
	public function getAuthPassword()
	{
		return $this->password;
	}

	/**
	 * Get the e-mail address where password reminders are sent.
	 *
	 * @return string
	 */
	public function getReminderEmail()
	{
		return $this->email;
	}




    public function getRememberToken()
    {
        return $this->remember_token;
    }

    public function setRememberToken($value)
    {
        $this->remember_token = $value;
    }

    public function getRememberTokenName()
    {
        return 'remember_token';
    }


}

app/controllers/UserController.php
<?php

class UserController extends BaseController {

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
      public function index()
	{
        $users = User::where('isadmin', '=', '1')->orderBy('name', 'ASC')->paginate(10);

        foreach($users as $user){
            $donorsAdded = Donor::where('staff_fk', '=', $user->id)->count();
            $user->donorsAdded = $donorsAdded;
        }

        return View::make('user.index')->with(array('users' => $users));

	}


	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		return View::make('user.add');
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store()
	{
        $rules = array(
            'name' => 'required|min:4',
            'email' => 'required|email|unique:users',
            'password' => 'required',
            'passwordConfirmation' => 'same:password'
        );

        $niceNames = array(
            'name' => 'име',
            'email' => 'e-mail',
            'password' => 'лозинка',
        );

        $validator = Validator::make(Input::all(), $rules);
        $validator->setAttributeNames($niceNames);
        if (!$validator->fails()) {


            $id = str_random(50);
            $user = new User();

            $user->id = $id;
            $user->fill(Input::all());

            $user->isadmin = 1;

            $hashedPassword = Hash::make(Input::get('password'));
            $user->password = $hashedPassword;

            $user->save();

            return Redirect::to('user');
        }
        else return Redirect::to('user/add')->withErrors($validator)->withInput();
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
        if($id == 'add'){
            return $this->create();
        }
        $user = User::find($id);
        if($user) {
		return  View::make('user.profile')->with(array(
                                                        'user' => $user,
                                                        'title' => $user->name . "'s profile page"
                                                         ));
        }

	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
        $user = User::find($id);

        if($user){
            return View::make('user.edit')->with('user', $user);
        }

        else {
            $user = 'empty';
            return View::make('user.edit')->with('user', $user);
        }
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{


        $user = User::find($id);

        $password = Input::get('password');
        if(isset($password) && $password != ''){
        $rules = array(
            'name' => 'required|min:4',
            'email' => 'required|email|unique:users',
            'password' => 'required',
            'passwordConfirmation' => 'same:password'
        );


        $niceNames = array(
            'name' => 'име',
            'email' => 'e-mail',
            'password' => 'лозинка',
        );
        }

        else{
            $rules = array(
                'name' => 'required|min:4',
                'email' => 'required|email|unique:users',
            );


            $niceNames = array(
                'name' => 'име',
                'email' => 'e-mail',
            );


            }


        if($user->email == Input::get('email')){
            $rules['email'] = 'required|email';
        }



        $validator = Validator::make(Input::all(), $rules);
        $validator->setAttributeNames($niceNames);
        if (!$validator->fails()) {


            if( null !== (Input::get('password'))){
                $hashedPassword = Hash::make(Input::get('password'));
                $user->password = $hashedPassword;
            }


            $user->name = Input::get('name');
            $user->email = Input::get('email');

            $user->save();

            return Redirect::to('users');
        }

        else{
            return Redirect::to('user/' . $user->id . '/edit')->withErrors($validator)->withInput();
        }

    }





	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		$user = User::find($id);

        if($user){
            $user->delete();
            $message = "Корисникот е успешно отстранет.";
            return Redirect::to('user.index')->with(array('message' => $message));
        }

        else {
            $message = "Настана грешка при бришење, Ве молиме пробајте повторно.";
            return Redirect::to('user.index')->with(array('message' => $message));
        }
    }

}

app/views/user/add.blade.php
@extends('master')
@section('content')




<div class="title_wrapper">
    <h3 class="title">Додавање на крводарител</h3>
</div>
<div class="add_admin_wrapper">


    <ul class="errors">
        @foreach($errors->all() as $message)
        <li>{{ $message }}</li>
        @endforeach
    </ul>
    <br/>
    <div class="add_admin_info">
    {{ Form::open(['route' => 'user.store']) }}

        {{ Form::label('name', 'Корисничко име') }} <br />
        {{ Form::text('name', null, ['placeholder' => 'Корисничко име']) }}
        <br />


        {{ Form::label('email', 'E-mail') }}
        <br />
        {{ Form::text('email', null, ['placeholder' => 'Е-mail']) }}

        <br />
        {{ Form::label('password', 'Лозинка') }}
        <br />
        {{ Form::password('password', null, ['placeholder' => 'Лозинка']) }}

        <br />
        {{ Form::label('passwordConfirmation', 'Потврда за лозинка') }}
        <br />
        {{ Form::password('passwordConfirmation', null, ['placeholder' => 'Лозинка']) }}


    </div>


    <div class="clear"></div>
    <div class="submit_wrapper">
        <br/>
        {{ Form::submit('Додади', ['class' => 'add_user_submit']) }}
    </div>

    {{ Form::close() }}
</div>


@stop

app/views/user/edit.blade.php
@extends('master')
@section('content')

<?php $errorImage = asset('images/google404.png'); ?>

@if($user != 'empty' && !empty($user))


<div class="title_wrapper">
    <h3 class="title">Промена на податоци за корисник</h3>
</div>

<div class="add_donor_wrapper">

    <ul class="errors">
        @foreach($errors->all() as $message)
        <li>{{ $message }}</li>
        @endforeach
    </ul><br/>
    <div class="add_admin_info">
        {{ Form::model($user, [ 'method' => 'PATCH', 'route' => ['user.update', $user->id]]) }}

        {{ Form::label('name', 'Корисничко име') }} <br />
        {{ Form::text('name', null, ['placeholder' => 'Корисничко име'], $user->name) }}
        <br />


        {{ Form::label('email', 'E-mail') }}
        <br />
        {{ Form::text('email', null, ['placeholder' => 'Е-mail'], $user->email) }}

        <br />
        {{ Form::label('password', 'Лозинка') }}
        <br />
        {{ Form::password('password', null, ['placeholder' => 'Лозинка']) }}

        <br />
        {{ Form::label('passwordConfirmation', 'Потврда за лозинка') }}
        <br />
        {{ Form::password('passwordConfirmation', null, ['placeholder' => 'Лозинка']) }}


    </div>




    <div class="clear"></div>
<br/>
        {{ Form::submit('Обнови', ['class' => 'update_user']) }}


    {{ Form::close() }}

</div>

@else

<div class="profile_wrapper">

    <div class="not_found">
        <img src="{{ $errorImage }}"/>
        <br/>
        {{ 'Акцијата не постои.'; }}
    </div>
</div>

@endif


@stop

app/views/user/index.blade.php
@extends('master')

@section('content')

{{ HTML::script('js/users-script.js') }}


<div class="title_wrapper">
<h3 class="title">Листа на корисници</h3>
</div>

    <table class="flat_table flat_table_1">
        <thead>
        <th>Корисничко име</th>
        <th>E-mail</th>
        <th>Додал/а</th>
        </thead>
        <tbody class="search_results">

        @foreach ($users as $user)

        <tr>
            <td> {{  link_to_route('user.show', $user->name, $user->id ) }} </td>

            <td> {{ $user->email }} </td>

            <td>
                @if ($user->donorsAdded == 1)
                    {{ $user->donorsAdded . '     крводарител'}}

                @else
                    {{ $user->donorsAdded . '     крводарители'}}
                @endif
            </td>
        </tr>

        @endforeach

        </tbody>


    </table>


    @if(isset($donors))
    {{ $donors->links(); }}
    @endif



@stop